import luxuryCollectionAestheticDark from "./assets/luxury-collection-aesthetic-dark.png";
import luxuryCollectionAestheticDull from "./assets/luxury-collection-aesthetic-dull.png";
import luxuryCollectionBlack from "./assets/luxury-collection-black.png";
import designedCollectionBlack from "./assets/designed-collection-black.svg?react";
import designedCollectionBlue from "./assets/designed-collection-blue.svg?react";
import designedCollectionWhite from "./assets/designed-collection-white.svg?react";
import gradientCollectionDark from "./assets/gradient-collection-dark.png";
import gradientCollectionFlorescent from "./assets/gradient-collection-florescent.png";
import gradientCollectionPurple from "./assets/gradient-collection-purple.png";
import limitedEditionBlue from "./assets/limited-edition-blue.png";
import limitedEditionTripleBlue from "./assets/limited-edition-triple-blue.png";
import limitedEditionVantablack from "./assets/limited-edition-vantablack.png";

const initialFrontFormInputs = {
  bgColor: "#1A59B2",
  bgGradient: "",
  bgGradientDirection: "",
  bgOpacity: "100",
  bgImage: "",
  textColor: "#ffffff",
  textOpacity: "100",
  fontSize: "20px",
  fontFamily: "Karantina",
  fontWeight: 400,
  isItalic: false,
  isUnderline: false,
  hasElementQrcode: false,
  hasElementNFC: false,
  elementColor: "#224455",
  elementOpacity: "100",
  logoImage: "",
};

const initialBackFormInputs = {
  bgColor: "#1A59B2",
  bgGradient: "",
  bgGradientDirection: "",
  bgOpacity: "100",
  bgImage: "",
  personTextColor: "#ffffff",
  personTextOpacity: "100",
  personFontSize: "20px",
  personFontFamily: "Karantina",
  personFontWeight: 400,
  isPersonItalic: false,
  isPersonUnderline: false,
  roleTextColor: "#ffffff",
  roleTextOpacity: "100",
  roleFontSize: "20px",
  roleFontFamily: "Karantina",
  roleFontWeight: 400,
  isRoleItalic: false,
  isRoleUnderline: false,
  hasElementQrcode: false,
  hasElementNFC: false,
  elementColor: "#224455",
  elementOpacity: "100",
};

card = {
  id: "",
  orientation: "",
  name: "",
  status: "",
  thumbnail: "",
  hasPaid: false,
  isBestSeller: false,
  frontSettings: {},
  backSettings: {},
};

profile = {
  cardRef: "",
};

cardTemplates = [
  {
    id: generateId(),
    orientation: "landscape",
    name: "custom",
    category: "Custom Collections",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: "",
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "#1A59B2",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      text: "Weber Outdoors",
      textColor: "#ffffff",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Dancing Script",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#ffffff",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "#2C2E2A",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "Person",
      personTextColor: "#ffffff",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Poppins",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "Role",
      roleTextColor: "#ffffff",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Poppins",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#ffffff",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Matte black",
    category: "Luxury Collections",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: luxuryCollectionAestheticDull,
    hasPaid: false,
    isBestSeller: true,
    frontSettings: {
      bgColor: "#2C2E2A",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      text: "Weber Outdoors",
      textColor: "#383939",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Dancing Script",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#383939",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "#2C2E2A",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "Person",
      personTextColor: "#383939",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Poppins",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "Role",
      roleTextColor: "#383939",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Poppins",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#383939",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Aesthetic dark grey",
    category: "Luxury Collections",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: luxuryCollectionAestheticDark,
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "#2E2E2E",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      text: "Weber Outdoors",
      textColor: "#393939",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Dancing Script",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#393939",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "#2E2E2E",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "Person",
      personTextColor: "#393939",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Poppins",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "Role",
      roleTextColor: "#393939",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Poppins",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#393939",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Aesthetic dull grey",
    category: "Luxury Collections",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: luxuryCollectionBlack,
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "#D2D5D3",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      text: "Weber Outdoors",
      textColor: "#F1F1F1",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Dancing Script",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#F1F1F1",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "#D2D5D3",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "Person",
      personTextColor: "#F1F1F1",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Poppins",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "Text",
      roleTextColor: "#F1F1F1",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Poppins",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#F1F1F1",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Matte Black 2",
    category: "Designed Collections",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: designedCollectionBlack,
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "#1E1E1E",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      text: "Grace Interiora",
      textColor: "#C39E75",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Molle",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#C39E75",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "#1E1E1E",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "Rose Goldy",
      personTextColor: "#C39E75",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Inter",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "Interior Designer",
      roleTextColor: "#C39E75",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Inter",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#C39E75",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Dark Blue",
    category: "Designed Collections",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: designedCollectionBlue,
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "#134B93",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      text: "MARRO'S WINGS",
      textColor: "#FFFCF8",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Koulen",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#FFFCF8",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "#1E1E1E",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "Mark Solomon",
      personTextColor: "#FFFCF8",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Inter",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "Real Estate Broker",
      roleTextColor: "#FFFCF8",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Inter",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#FFFCF8",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Pure White",
    category: "Designed Collections",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: designedCollectionWhite,
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "#134B93",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      text: "FASHION FOR ALL",
      textColor: "#FFFCF8",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Koulen",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#FFFCF8",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "#1E1E1E",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "Sarah Mathew",
      personTextColor: "#FFFCF8",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Inter",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "Owner | Designer",
      roleTextColor: "#FFFCF8",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Inter",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#FFFCF8",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Purple - Yellow Gradient",
    category: "Gradient Edition",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: gradientCollectionPurple,
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "",
      bgGradientStart: "#CFACD2",
      bgGradientCenter: "#C07CB3",
      bgGradientEnd: "#F6C391",
      bgGradientDirection: "90deg",
      bgOpacity: "100",
      bgImage: "",
      text: "",
      textColor: "#FDFDFB",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Inter",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#FDFDFB",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "",
      bgGradientStart: "#CFACD2",
      bgGradientCenter: "#C07CB3",
      bgGradientEnd: "#F6C391",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "JOHN DOE",
      personTextColor: "#FDFDFB",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Inter",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "",
      roleTextColor: "#FDFDFB",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Inter",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#000",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Florescent Gradient",
    category: "Gradient Edition",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: gradientCollectionFlorescent,
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "",
      bgGradientStart: "#A9E1AF",
      bgGradientCenter: "#EACEEE",
      bgGradientEnd: "#D6FEFE",
      bgGradientDirection: "90deg",
      bgOpacity: "100",
      bgImage: "",
      text: "",
      textColor: "#FFFFFF",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Inter",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#000",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "",
      bgGradientStart: "#D6FEFE",
      bgGradientCenter: "#EACEEE",
      bgGradientEnd: "#A9E1AF",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "JOHN DOE",
      personTextColor: "#FFFFFF",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Inter",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "",
      roleTextColor: "#FFFFFF",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Inter",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#000",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Dark Gradient",
    category: "Gradient Edition",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: gradientCollectionFlorescent,
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "",
      bgGradientStart: "#F9BC54",
      bgGradientCenter: "#E73E8E",
      bgGradientEnd: "#2D50A2",
      bgGradientDirection: "45deg",
      bgOpacity: "100",
      bgImage: "",
      text: "",
      textColor: "#000",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Inter",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#000",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "",
      bgGradientStart: "#F9BC54",
      bgGradientCenter: "#E73E8E",
      bgGradientEnd: "#2D50A2",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "JOHN DOE",
      personTextColor: "#000",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Inter",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "",
      roleTextColor: "#000",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Inter",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#000",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Vantablack NFC",
    category: "Limited Edition",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: limitedEditionVantablack,
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "#010101",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      text: "",
      textColor: "#D2AE7B",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Koulen",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#D2AE7B",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "#1E1E1E",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "JOHN DOE",
      personTextColor: "#D2AE7B",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Inter",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "",
      roleTextColor: "#D2AE7B",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Inter",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#D2AE7B",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Blue - Purple Gradient",
    category: "Limited Edition",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: limitedEditionBlue,
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "",
      bgGradientStart: "#5EA5D4",
      bgGradientCenter: "#3F5BA5",
      bgGradientEnd: "#765DA6",
      bgGradientDirection: "90deg",
      bgOpacity: "100",
      bgImage: "",
      text: "",
      textColor: "#FDFDFB",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Koulen",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#FDFDFB",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "#1E1E1E",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "JOHN DOE",
      personTextColor: "#FDFDFB",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Inter",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "",
      roleTextColor: "#FDFDFB",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Inter",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#000",
      elementOpacity: "100",
    },
  },
  {
    id: generateId(),
    orientation: "landscape",
    name: "Triple blue Gradient",
    category: "Limited Edition",
    description: "Customise: card design & digital profile",
    price: 2000,
    status: "under-creation",
    thumbnail: limitedEditionTripleBlue,
    hasPaid: false,
    isBestSeller: false,
    frontSettings: {
      bgColor: "",
      bgGradientStart: "#A8CAE5",
      bgGradientCenter: "#E7B0D0",
      bgGradientEnd: "#3C74B9",
      bgGradientDirection: "90deg",
      bgOpacity: "100",
      bgImage: "",
      text: "",
      textColor: "#FDFDFB",
      textOpacity: "100",
      fontSize: "20px",
      fontFamily: "Koulen",
      fontWeight: 400,
      isItalic: true,
      isUnderline: false,
      hasElementQrcode: false,
      hasElementNFC: false,
      elementColor: "#FDFDFB",
      elementOpacity: "100",
      logoImage: "",
    },
    backSettings: {
      bgColor: "#1E1E1E",
      bgGradientStart: "",
      bgGradientCenter: "",
      bgGradientEnd: "",
      bgGradientDirection: "",
      bgOpacity: "100",
      bgImage: "",
      personText: "JOHN DOE",
      personTextColor: "#FDFDFB",
      personTextOpacity: "100",
      personFontSize: "20px",
      personFontFamily: "Inter",
      personFontWeight: 400,
      isPersonItalic: false,
      isPersonUnderline: false,
      roleText: "",
      roleTextColor: "#FDFDFB",
      roleTextOpacity: "100",
      roleFontSize: "20px",
      roleFontFamily: "Inter",
      roleFontWeight: 400,
      isRoleItalic: false,
      isRoleUnderline: false,
      hasElementQrcode: true,
      hasElementNFC: true,
      elementColor: "#000",
      elementOpacity: "100",
    },
  },
];
